services:

  abp_host:
    image: abpgroup/host-local
    build:
      context: ..
      dockerfile: src/ABPGroup.Web.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__Default: "${ConnectionStrings__Default}"
      App__ServerRootAddress: "http://localhost:44311/"
      App__ClientRootAddress: "http://localhost:4200/"
      App__CorsOrigins: "http://localhost:4200"
      TZ: "America/Toronto"
      PORT: "80"
      Kestrel__Endpoints__Http__Url: "http://+:80"
    ports:
      - "44311:80"
    volumes:
      - "./Host-Logs:/app/App_Data/Logs"
    restart: always
